### ISSUE TITLE
Can't access external drives

### ISSUE THREAD

**Issue by ghost** [Eshaan7/RenameThemSubs#6]
```
Traceback (most recent call last):
  File "renamethemsubs.py", line 95, in <module>
    main()
  File "renamethemsubs.py", line 91, in main
    diff_path()
  File "renamethemsubs.py", line 33, in diff_path
    for name in os.listdir(vid_path):
FileNotFoundError: [Errno 2] No such file or directory: '"/mnt/external/Traceback (most recent call last):
  File "renamethemsubs.py", line 95, in <module>
    main()
  File "renamethemsubs.py", line 91, in main
    diff_path()
  File "renamethemsubs.py", line 33, in diff_path
    for name in os.listdir(vid_path):
FileNotFoundError: [Errno 2] No such file or directory: '"/mnt/external/"'
```

I had the copy the .py file to this directory -- the script then renamed the subtitles correctly. I'm using Fedora 32.

**Comment by eshaan7** [comment]
Thanks for your report. I think this is not related to this application, but python only because some extra work needs to be done when accessing files inside a mounted volume. Permissions also comes into place, because if you ran the script as a normal user it probably won't have access to mounted volumes. 

Also, can you please check if the `/mnt/external` path you provided was correct ? 

In any case, you may want to use the web app, https://renamethemsubs.herokuapp.com/ then you won't have to deal with such issues.

**Comment by ghost** [comment]
> Also, can you please check if the `/mnt/external` path you provided was correct ?

Yes, that's where I've mounted my HDD.

I prefer local programs.

**Comment by ghost** [comment]
The issue may not have relevance anymore.
